### ISSUE TITLE
With the code it's ValueError: time data

### ISSUE THREAD

**Issue by taraldesai** [priitp2/trctools#1]
Hi,

I was looking at this and trying to give it a try

./trc2db.py --dbdir /Users/XXXX/TrcFile /Users/XXXX/TrcFile/*

[1/1] processing file /Users/XXXX/TrcFile/TRACE1.trc
Traceback (most recent call last):
  File "/Users/XXXX/Tools/trctools/./trc2db.py", line 46, in <module>
    lines = trcparser.process_file(tracker, fname, args.orphans)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/XXXX/Tools/trctools/parser.py", line 118, in process_file
    ts2 = datetime.datetime.strptime(match.group(3), '%Y-%m-%dT%H:%M:%S.%f%z')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2024-01-16 11:29:17.665' does not match format '%Y-%m-%dT%H:%M:%S.%f%z'

**Comment by priitp2** [comment]
Hi,

Can you send me the trace file?

**Comment by priitp2** [comment]
Nevermind, I think I just fixed the time zone issue. Just do a git pull,
install tzinfo module, and try again ;)
